// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-send-message': string;
  'action-send-message-other': string;
  'form': string;
  'input': string;
}
declare var cssExports: CssExports;
export = cssExports;
