// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'trade': string;
  'trade-is-fetching': string;
  'trade-not-found': string;
}
declare var cssExports: CssExports;
export = cssExports;
