// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat-message': string;
  'message-avatar': string;
  'message-body': string;
  'message-body-left': string;
  'message-body-right': string;
  'message-date': string;
  'message-date-left': string;
  'message-date-right': string;
  'message-text': string;
  'message-text-left': string;
  'message-text-right': string;
}
declare var cssExports: CssExports;
export = cssExports;
