// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'currency': string;
  'link': string;
  'money-values': string;
  'paid-status-not-paid': string;
  'paid-status-paid': string;
  'payment-method': string;
  'trade-chat-notification': string;
  'trade-chat-notification-read': string;
  'trade-chat-notification-unread': string;
  'trade-info': string;
  'trade-item': string;
  'trade-status': string;
  'trading-with-avatar': string;
  'trading-with-status': string;
  'user-login': string;
  'user-status': string;
}
declare var cssExports: CssExports;
export = cssExports;
