// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'trades-fetching': string;
  'trades-list': string;
}
declare var cssExports: CssExports;
export = cssExports;
