// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-delete-trade': string;
  'chat-header': string;
  'messages': string;
  'payment-method': string;
  'reputation-negative': string;
  'reputation-positive': string;
  'trade-chat': string;
  'trading-with': string;
  'trading-with-login': string;
}
declare var cssExports: CssExports;
export = cssExports;
