// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'no-trade-selected': string;
  'time': string;
  'trade-info': string;
}
declare var cssExports: CssExports;
export = cssExports;
