// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-release-cryptocurrency': string;
  'block': string;
  'block-amount-cryptocurrency-value': string;
  'block-amount-currency-value': string;
  'block-hash-value': string;
  'block-status-value': string;
  'block-status-value-not-paid': string;
  'block-status-value-paid': string;
  'block-title': string;
  'block-user-trades-counter': string;
  'description': string;
  'info-blocks': string;
  'reputation-negative': string;
  'reputation-positive': string;
  'time': string;
  'trade-info': string;
  'trading-with': string;
}
declare var cssExports: CssExports;
export = cssExports;
